# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Trait/Documents/uBlaze/frogger/frogger.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_0/microblaze_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'microblaze_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Trait/Documents/uBlaze/frogger/frogger.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_0/microblaze_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Trait/Documents/uBlaze/frogger/frogger.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_0/microblaze_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'microblaze_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Trait/Documents/uBlaze/frogger/frogger.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_0/microblaze_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
